# Generated by Django 4.2.8 on 2023-12-27 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='PictureUS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título de imagen')),
                ('image', models.ImageField(upload_to='picturesUS', verbose_name='Imagen')),
                ('linkFb', models.CharField(max_length=300, verbose_name='Enlace de facebook')),
                ('linkIg', models.CharField(max_length=300, verbose_name='Enlace de Instagram')),
                ('linkX', models.CharField(max_length=300, verbose_name='Enlace de X')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'uspicture',
                'verbose_name_plural': 'uspcitures',
                'ordering': ['-created'],
            },
        ),
    ]
