# Generated by Django 4.2.8 on 2023-12-27 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pictureus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del partnet')),
                ('profilepicture', models.ImageField(upload_to='profilepic', verbose_name='Imagen')),
                ('since', models.DateField(verbose_name='Fecha de alta del partner')),
                ('position', models.CharField(max_length=300, verbose_name='Puesto del partner')),
                ('contract', models.CharField(max_length=200, verbose_name='Nombre del partnet')),
                ('description', models.TextField(verbose_name='Descripcion del partner')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'partner',
                'verbose_name_plural': 'partners',
                'ordering': ['-created'],
            },
        ),
    ]
