# Generated by Django 5.0 on 2023-12-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nombre de la imagen')),
                ('photo', models.ImageField(upload_to='works', verbose_name='Imagen')),
                ('description', models.CharField(max_length=200, verbose_name='Descripcion del trabajo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'work',
                'verbose_name_plural': 'works',
                'ordering': ['-created'],
            },
        ),
        migrations.AlterField(
            model_name='partner',
            name='contract',
            field=models.CharField(max_length=200, verbose_name='Contracion del partnet'),
        ),
    ]
